### ISSUE TITLE
Memurai it is not cross-plataform

### ISSUE THREAD

**Issue by rafaga** [bzoz/ed-ltd-seller#1]
Have you considered using another database, because memurai is only for Windows.

**Comment by bzoz** [comment]
Memurai is 100% compatible with Redis, so you can use that on other platforms.

**Comment by bzoz** [comment]
Updated the readme and made the app look for Redis on the non-Windows platforms: https://github.com/bzoz/ed-ltd-seller/commit/97ad9273c404b12241f8a37f6d2cc1a1b78c7659
